columns:
  longitude: float
  latitude: float
  housing_median_age: float
  total_rooms: float
  total_bedrooms: float
  population: float
  households: float
  median_income: float
  ocean_proximity: str
  median_house_value: float


TARGET_COLUMN:
  name: median_house_value 

  
